// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbqwqqrxevgieknqavuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhicXdxcXJ4ZXZnaWVrbnFhdnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NjExMTYsImV4cCI6MjA2MjIzNzExNn0.iJeIFc8Upj99aCilmFd-sZHsAHvqk23UAcib-JqKLMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);